# Generated by Django 6.0.6 on 2026-07-19 13:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('code_categorie', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('libelle_categorie', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'db_table': 'categorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentreSante',
            fields=[
                ('code_centre', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_centre', models.CharField(max_length=150)),
                ('contact_centre', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'centre de santé',
                'db_table': 'centre_sante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offrir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'offrir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultatDuRapport',
            fields=[
                ('code_resultat', models.AutoField(primary_key=True, serialize=False)),
                ('ratio', models.FloatField()),
                ('statut', models.CharField(choices=[('sous_equipee', 'Sous équipée'), ('equipee', 'Équipée')], max_length=20)),
                ('date_rapport', models.DateTimeField()),
                ('nombre_centre', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Résultat du rapport',
                'db_table': 'resultat_du_rapport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('code_service', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('libelle_service', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'service',
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SousPrefecture',
            fields=[
                ('code_souspref', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('libelle_souspref', models.CharField(max_length=150)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('habitant', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sous-préfecture',
                'db_table': 'sous_prefecture',
                'managed': False,
            },
        ),
    ]
